### ISSUE TITLE
Ignition v3 to-do's

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/ignition#16]
## Front-end issues

- [x] Safari build is broken (regex in TailwindCSS build)
- [x] Tag pre-release versions
- [x] Show full context key on hover
- [x] Figure out solution contracts in Ignition v3
- [x] Readme
- [x] Error boundaries
- [x] Share admin URLs
- [ ] Error message when failed to save settings
- [x] Remove Laravel docs in PHP agnostic version
- [x] Figure out ignition-ui release on NPM
- [x] Switch back to HighlightJS (only one with Blade support)
- [x] Export SQL queries from exception in `ErrorCard`
- [x] Hide sections that have no content
- [x] Highlighted stack frames should be cached when switching frames
- [x] Livewire context needs to be ported
- [x] Active indicator for context
- [x] Syntax highlighting for CURL & SQL `CodeSnippet`s 
- [x] Debug section should disappear if there are no debug items
- [x] Link to Telescope is missing
- [x] Clicking outside of share/settings dialog should close the dialog
- [x] Add extra information to settings dialog about saving to `~/.ignition.json`
- [x] Fix docs link
- [x] Refactor data models in all packages
- [x] Make sure the first active frame is always an application frame
- [x] Stack frames without a classname should show filename
- [x] ShikiJS local, no external dependencies (or Prism/Highlightjs)
- [x] Ignore full path prefix option for `RelaxedFilePath` component (`/users/alex/projects/sail/index.php` -> `index.php`)
- [x] Remove 🧨
- [x] Test PHP view exceptions (so not blade)
- [x] Docs site in share popup
- [x] Remove exception class dropdown

## Layout/design issues

- [x] Debug section styling
- [x] Symfony dumps additional styling (e.g. search input & darkmode)
- [x] Icons: preferable bundled as SVGs. Definitely needs to be local
- [x] Livewire icon
- [x] "Settings saved" after saving settings should be styled
- [x] Git context styling
- [x] View data layout (key-value data in een `DefinitionList.Row`)
- [x] `DefinitionList.Row` boolean value styling (currently weirdly spaced icons)
- [x] Min-height for stacktrace (gets small when there's just a couple of lines of code)
- [x] ~Multi-column layout~?
- [x] Click outside Share/Settings closes dropdown
- [x] Clickable context menu
- [x] Anchor offset
- [x] Solution runner styling
- [x] Can't click on the lower half of debug tabs

## Back-end/PHP issues

- [x] User's local dotfile settings get overwritten by project settings
- [x] Modify Flare API to accept shares with just 3 context options
- [x] PR namespace change to Livewire
- [x] Custom blade engine revision: do we still need it if we don't log view data?

## Maybe later

- [ ] Show call parameters in every frame
- [ ] Support previous exceptions
- [ ] Make expanded `CodeSnippet` collapsable again?
- [ ] Look into alternatives for share admin URL?
- [x] Keep code colors consistent between SFdumps and highlight.js

**Comment by AlexVanderbist** [comment]
- [ ] gebeurt ook nog iets vreemd met lange stacktrace files en line numbers:
![image](https://user-images.githubusercontent.com/6287961/148207573-37ad3f20-fb3e-4a6f-afa2-c6b701d699c2.png)

**Comment by willemvb** [comment]
- [ ] Little glitch in highlighted SQL
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1336390/150502148-9f4ebcaa-5935-4a30-b93e-f85571b1fb7a.png">

**Comment by pixeldevsio** [comment]
Can we change the Views link to be an option as to what program we want to open it in? Currently it's set to PHPStorm
<img width="888" alt="Screen Shot 2022-03-18 at 11 27 19" src="https://user-images.githubusercontent.com/59432382/159032510-1c61afb4-8458-43d0-8226-b9e41ed34907.png">

**Comment by willemvb** [comment]
Hej @pixeldevsio,

This is configurable under the settings in the top right:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1336390/159445297-2e64dbe7-f05c-4391-8b2b-68db7772766b.png">

Hope this helps!
